name: Build APK

on:
  push:
    branches:
      - Set_CICD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.24.1'

      - name: Store secrets in json file
        run: |
          mkdir -p assets/secret
          echo '{ "rate_api_key": "${{ secrets.RATE_API_KEY }}", "news_api_key": "${{ secrets.NEWS_API_KEY }}" }' > assets/secret/secret.json

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
